version: "3"

services:

  php:
    container_name: php
    image: dbjpanda/drupal-on-docker-php
    volumes:
      - ./code:/var/www/${SITE_NAME}:cached
    working_dir: /var/www/${SITE_NAME}


  nginx:
    container_name: nginx
    image: dbjpanda/drupal-on-docker-nginx
    volumes:
      - ./code:/var/www/${SITE_NAME}:cached
    ports:
      - ${NGINX_PORT}:80
    working_dir: /var/www/${SITE_NAME}
    environment:
      SITE_NAME: ${SITE_NAME}
      DRUPAL_VERSION: ${DRUPAL_VERSION}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      MYSQL_PORT: ${MYSQL_PORT}

  mariadb:
    container_name: mariadb
    image: dbjpanda/drupal-on-docker-mariadb
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}